### PR TITLE
Revert "Pushjet support"

### PR DESCRIPTION
**Pull request by caronc**
Reverts caronc/nzb-notify#23

@paradix: Just reverting changes for now because of ticket #24 raised from it.

PushJet looks great and your efforts are too, but will need to clean up a few entries to make it compatible with everyone else.  I'll do a more in-depth code review in a few hours when i'm home.

### CODE REVIEW

**Comment by paradix** [comment]
Ok, hmm thats wierd. Don't see the connection between mmosts and pjet yet

**Comment by paradix** [comment]
Could be actually helpful to get the whole stack trace from the error message

**Comment by paradix** [comment]
I have been trying to reproduce the issue but couldn't really.

**Comment by caronc** [comment]
Thanks for your efforts! I still want to merge your code, reverting back just made the most sense at the time. I didn't have time to look at the code in detail last night.

What's important is that it working for you. If you wouldn't mind, could you go ahead and create another pull request? I'll reply inline to anything I find. I plan on checking out your forked master version and seeing what happens for me (hopefully sometime this weekend if not before).

It might be a Python version issue. It may also just be a library available (globally) in your environment but not in the _Notify_ shipped to others. Either way, we'll figure it out.

**Comment by paradix** [comment]
Well :) I was looking for bugs and the problem is the missing dependency to decorator. Stupid me, I just had the module already installed so didn't pop up as an issue over here.
I'll had a look if you can use it as a Notify library.

**Pull request merged**
