### PR TITLE
Allow SABnzbd to pass URLs as environment variable

### PR DESCRIPTION
**Pull request by Safihre**
As discussed here:
https://github.com/sabnzbd/sabnzbd/issues/2549#issuecomment-1569952141

### CODE REVIEW

**Comment by caronc** [comment]
Were you planning on making any more changes? Just give me the word and I'll merge it 👍

**Comment by caronc** [comment]
Going to roll with the difference in timezones is why you're not responding. I'm suspecting you pulled it off before you went to sleep 😴. Merging

**Comment by Safihre** [comment]
Thanks :) I did my own testing, let's see if it was thorough enough.

**Comment by jeefberkey** [comment]
Hi, sorry to resurrect a dead issue, but can there be a release with this change in it? My linuxserver/sabnzbd container is currently unable to send notifications until this env var is respected

**Comment by caronc** [comment]
I'm sorry, absolutely. I'm do this first thing in the morning

**Comment by jeefberkey** [comment]
Awesome, thank you!

**Comment by caronc** [comment]
[done](https://github.com/caronc/nzb-notify/releases/tag/v1.0.1) :tada:

**Pull request merged**
